### PR TITLE
Haungrui777/master

### PR DESCRIPTION
**Pull request by JulianFeinauer**
This is a PR that extends #2 with some adjustments.

### CODE REVIEW

**Comment by JulianFeinauer** [comment]
@haungrui777 could you have a look at the failing lint-css command in the build? I think we can easily merge it when this is fixed.

**Review by NiklasMerz — APPROVED** [review]

**Comment by haungrui777** [comment]
> @haungrui777 could you have a look at the failing lint-css command in the build? I think we can easily merge it when this is fixed.

fixed the css lint error

**Comment by NiklasMerz** [comment]
@JulianFeinauer Are we not ready to merge?

**Comment by JulianFeinauer** [comment]
Thanks @haungrui777 and regarding your question @NiklasMerz there are still issues in the lint-css phase but I woild be fine in deactivating it for now so that we have a green Branch before merging. WDYT?

**Comment by NiklasMerz** [comment]
Check out this PR for your branch: https://github.com/JulianFeinauer/iotdb-web-workbench/pull/3

**Comment by JulianFeinauer** [comment]
Will merge that now. Big thanks to @haungrui777 and @NiklasMerz ! 🎉

**Pull request merged**
